# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

PROJECT_FILENAME = "BundesIdent"
SCHEME_NAME = "BundesIdent"

def to_boolean(str)
  str.downcase == 'true' || str == '1'
end

platform :ios do

  before_all do
    ENV["LC_ALL"] = "de_DE.UTF-8"
    ENV["LANG"] = "de_DE.UTF-8"

    ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"
  end

  desc 'Get App Version'
  lane :getAppVersion do |options|
    rel_path = options[:rel_path] || '../'
    project = Xcodeproj::Project.open("#{rel_path}#{PROJECT_FILENAME}.xcodeproj")
    version = project.build_settings('Release Production')['MARKETING_VERSION']
    puts "Current version: #{version}"
    version
  end

  desc "Build"
  lane :build_for_testing do
    scan(
      project: "#{PROJECT_FILENAME}.xcodeproj",
      scheme: SCHEME_NAME,
      cloned_source_packages_path: '.swift-packages',
      xcpretty_args: '--color',
      build_for_testing: true,
      output_xctestrun: true,
      clean: true,
      derived_data_path: "./DerivedData"
    )
  end

  desc "Runs unit tests without building"
  lane :test_without_building do | options |
    begin
      testPlan = options[:testplan] || "AllTests"
      device = options[:device] || "iPhone 14"
      
      run_tests(
        scheme: SCHEME_NAME,
        derived_data_path: "./DerivedData",
        cloned_source_packages_path: '.swift-packages',
        test_without_building: true,
        testplan: testPlan,
        devices: [device],
        skip_detect_devices: true,
        prelaunch_simulator: false,
        skip_package_dependencies_resolution: true,
        disable_package_automatic_updates: true,
        result_bundle: true,
        code_coverage: true,
        reset_simulator: true,
        app_identifier: 'de.bund.digitalservice.UseID-Preview',
        concurrent_workers: 7,
        output_style: "raw",
        output_types: "",
        number_of_retries: 0,
        ensure_devices_found: true
      )
    rescue
      UI.user_error!("Tests did fail, please check logs above or #{SCHEME_NAME}.xcresult.zip")
    ensure
      trainer(
        output_directory: "fastlane/test_output/",
        path: "fastlane/test_output/",
        extension: ".junit",
        fail_build: false
      )

      zip(
        path: "fastlane/test_output/#{SCHEME_NAME}.xcresult",
        output_path: "fastlane/test_output/#{SCHEME_NAME}.xcresult.zip",
        verbose: false
      )
    end
  end

  desc 'Test'
  lane :test do |options|
    build_for_testing(options)
    test_without_building(options)
  end

  desc 'Check Localizables are sorted'
  lane :checklocalizables do
    sh("../scripts/checksort.sh")
  end

  desc 'Lint with SwiftFormat'
  lane :swiftformatlint do
    swiftformat( 
      dryrun: true,
      lint: true
    )
  end

  desc 'Lint code'
  lane :lint do
    swiftlint(
      executable: "swiftlint",
      mode: :lint,
      output_file: "swiftlint.html",
      strict: true,
      quiet: true,
      no_cache: false,
      reporter: "html"
    )
  end

  desc 'Trigger Preview'
  lane :preview do |options|
    ensure_git_status_clean
    buildPreview(options)
    deliverPreview(options)
  end

  desc 'Build Preview'
  lane :buildPreview do |options|
    build_app(
      project: "#{PROJECT_FILENAME}.xcodeproj",
      configuration: 'Release Preview',
      clean: true,
      scheme: SCHEME_NAME,
      cloned_source_packages_path: '.swift-packages',
      xcconfig: "#{SCHEME_NAME}/Preview.xcconfig",
      export_method: 'app-store',
      export_options: {
        provisioningProfiles: { 
          "de.bund.digitalservice.UseID-Preview" => "UseID Preview - Distribution"
        }
      },
      include_bitcode: false
    )

    artifcats = "../artifacts"
    Dir.mkdir(artifcats) unless Dir.exists?(artifcats)
    backup_xcarchive(destination: "artifacts", versioned: false)
  end

  desc 'Deliver Preview'
  lane :deliverPreview do |options|
    make_screenshots = options[:screenshots] == true
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'digitalservice',
      project_slug: 'useid-preview-ios',
    )
    upload_to_testflight(
      api_key_path: ENV['APPSTORECONNECT_API_KEY_PATH'],
      skip_waiting_for_build_processing: true
    )
  end

  desc 'Trigger Production'
  lane :production do |options|
    ensure_git_status_clean
    buildProduction(options)
    deliverProduction(options)
  end

  desc 'Build Production'
  lane :buildProduction do |options|
    build_app(
      project: "#{PROJECT_FILENAME}.xcodeproj",
      configuration: 'Release Production',
      clean: true,
      scheme: SCHEME_NAME,
      cloned_source_packages_path: '.swift-packages',
      xcconfig: "#{SCHEME_NAME}/Release.xcconfig",
      export_method: 'app-store',
      export_options: {
        provisioningProfiles: { 
          "de.bund.digitalservice.UseID" => "UseID - Distribution"
        }
      },
      include_bitcode: false
    )

    artifcats = "../artifacts"
    Dir.mkdir(artifcats) unless Dir.exists?(artifcats)
    backup_xcarchive(destination: "artifacts", versioned: false)
  end

  desc 'Deliver Production'
  lane :deliverProduction do |options|
    make_screenshots = options[:screenshots] == true
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'digitalservice',
      project_slug: 'useid-ios',
    )
    upload_to_testflight(
      api_key_path: ENV['APPSTORECONNECT_API_KEY_PATH'],
      skip_waiting_for_build_processing: true
    )
  end

  desc 'Bump version'
  lane :bumpVersion do |options|
    bumpBuildNumber = to_boolean(ENV['BUMP_BUILD_NUMBER'] || options[:bumpBuildNumber] || 'false')
    version = ENV['VERSION'] || options[:version] || ''

    puts "Bumping version with version:#{version} bumpBuildNumber:#{bumpBuildNumber}"
    
    oldTag = "#{getAppVersion}-#{get_build_number}"
    unless version.empty?
      updateAppVersion(version: version)
    end
    if bumpBuildNumber
      increment_build_number
    end
    newTag = "#{getAppVersion}-#{get_build_number}"

    next if oldTag == newTag

    puts "Writing new tag #{newTag} to github env: #{ENV['GITHUB_ENV']}"
    sh("echo 'GIT_TAG=#{newTag}' >> #{ENV['GITHUB_ENV']}")

    commit_version_bump(xcodeproj: "#{PROJECT_FILENAME}.xcodeproj")
    add_git_tag(tag: newTag)
    push_to_git_remote(tags: false, push_options: ["tag #{newTag}"])
  end

  desc 'Update app version'
  lane :updateAppVersion do |options|
    new_app_version = options[:version]
    return if new_app_version.nil? || new_app_version.empty?

    puts "Updating to app version: #{new_app_version}"
    rel_path = options[:rel_path] || '../'
    
    project = Xcodeproj::Project.open("#{rel_path}#{PROJECT_FILENAME}.xcodeproj")
    project.build_configuration_list.build_configurations.each do |build_configuration|
      puts "Bumping version of #{build_configuration} from \
            #{build_configuration.build_settings['MARKETING_VERSION']} to #{new_app_version}"
      build_configuration.build_settings['MARKETING_VERSION'] = new_app_version
    end
    project.save

    puts "Saved project. Returning #{getAppVersion}"
  end
end
