# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

ENV["LC_ALL"] = "de_DE.UTF-8"
ENV["LANG"] = "de_DE.UTF-8"

ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"

default_platform(:ios)

PROJECT_FILENAME = "BundID"

platform :ios do

  desc 'Get App Version'
  lane :getAppVersion do |options|
    rel_path = options[:rel_path] || '../'
    project = Xcodeproj::Project.open("#{rel_path}#{PROJECT_FILENAME}.xcodeproj")
    version = project.build_settings('Release')['MARKETING_VERSION']
    puts "Current version: #{version}"
    version
  end

  desc "Build"
  lane :build do
    scan(
      project: "#{PROJECT_FILENAME}.xcodeproj",
      scheme: 'BundID',
      cloned_source_packages_path: '.swift-packages',
      xcpretty_args: '--color',
      build_for_testing: true,
      clean: true
    )
  end

  desc "Runs unit tests without building"
  lane :test_without_building do | options |
    begin
      testPlan = options[:testplan] || "AllTests"
      run_tests(
        scheme: "BundID",
        cloned_source_packages_path: '.swift-packages',
        test_without_building: true,
        testplan: testPlan,
        devices: ["iPhone 13"],
        skip_detect_devices: true,
        prelaunch_simulator: false,
        skip_package_dependencies_resolution: true,
        disable_package_automatic_updates: true,
        result_bundle: true,
        code_coverage: true,
        reset_simulator: true,
        app_identifier: 'com.example.BundID',
        concurrent_workers: 7,
        output_style: "raw",
        output_types: "",
        number_of_retries: 0
      )
    rescue
      UI.user_error!("Tests did fail, please check logs above or BundID.xcresult.zip")
    ensure
      trainer(
        output_directory: "fastlane/test_output/",
        path: "fastlane/test_output/",
        extension: ".junit",
        fail_build: false
      )

      zip(
        path: "fastlane/test_output/BundID.xcresult",
        output_path: "fastlane/test_output/BundID.xcresult.zip",
        verbose: false
      )
    end
  end

  desc 'Test'
  lane :test do |options|
    build(options)
    test_without_building(options)
  end

  desc 'Lint code'
  lane :lint do
    swiftlint(
      executable: "swiftlint",
      mode: :lint,
      output_file: "swiftlint.html",
      config_file: ".swiftlint.yml",
      strict: true,
      quiet: true,
      no_cache: false,
      reporter: "html"
    )
  end

  desc 'Trigger Release'
  lane :release do |options|
    buildRelease(options)
    deliverRelease(options)
  end

  desc 'Build Release'
  lane :buildRelease do |_options|
    ensure_git_status_clean

    build_app(
      project: "#{PROJECT_FILENAME}.xcodeproj",
      configuration: 'Release',
      clean: true,
      scheme: 'BundID',
      cloned_source_packages_path: '.swift-packages',
      export_method: 'app-store'
    )

    version = getAppVersion
    build_number = get_build_number

    add_git_tag(tag: "#{version}-#{build_number}")
    push_to_git_remote
  end

  desc 'Deliver Release'
  lane :deliverRelease do |options|
    make_screenshots = options[:screenshots] == true
    deliver(
      force: true,
      submission_information: {
        add_id_info_uses_idfa: false
      },
      skip_screenshots: !make_screenshots,
      precheck_include_in_app_purchases: false
    )
  end

  desc 'Bump version'
  lane :bumpVersion do
    increment_build_number

    version = getAppVersion
    build_number = get_build_number

    commit_version_bump(xcodeproj: "#{PROJECT_FILENAME}.xcodeproj")
    add_git_tag(tag: "#{version}-#{build_number}")
  end
end
